### ISSUE TITLE
.env.docker overrides settings of .env

### ISSUE THREAD

**Issue by gcerar** [postgresml/postgresml#513]
Hi,

Thank you for the project and your effort.

**Issue:** I was experimenting with deploying PostgresML on a workstation and accessing the dashboard from another machine. I bumped into the issue where I couldn't override `DJANGO_ALLOWED_HOSTS`. I tried to set environment variables through `docker-compose.yml` (see example below) and through `.env` file, but according to Django's debug/error page, DJANGO_ALLOWED_HOSTS (`ALLOWED_HOSTS` after parsing) was unchanged.

```yaml
  dashboard:
    depends_on:
      - postgres
    build:
      context: ./pgml-dashboard/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_CSRF_TRUSTED_ORIGINS
    command:
      - python3
      - manage.py
      - runserver
      - 0.0.0.0:8000
```

**Workaround:** After digging into the code, I noticed that file `./pgml-dashboard/docker/.env.docker` overrides everything I define in the environment (in `docker-compose.yaml`) and `.env` at the root or `./pgml-dashboard`. Commenting out the `DJANGO_ALLOWED_HOSTS` there solves the issue.

**I see two solutions to the problem:**
1. Remove the `./pgml-dashboard/docker/.env.docker` file and introduce "global" dotenv at the root of the project. This way, environment variables would be passed from `.env` or compose file into the containers. In docker-compose you may define fallback values, if those are not defined anywhere.
2. Add documentation to README describing where to change variables for the dashboard.

Kind regards,
Gregor
